### ISSUE TITLE
Disaggregation method

### ISSUE THREAD

**Issue by spencer-rdh** [alarm-redist/census-2020#13]
Hello! I'm looking to learn about your disaggregation process from precincts to blocks a little more. In your code [00_build_vest.R](https://github.com/alarm-redist/census-2020/blob/main/R/00_build_vest.R) it looks like you make the block file here at line 77 ` dec <- build_dec('block', state = state, geometry = FALSE, groups = 'all', year = 2010)` for 2010 and then assign the votes down based on the 2010 VAP ratio here (lines 86-89) `elec_at_2010 <- elec_at_2010 %>%
          mutate(!!election := estimate_down(
            value = vest[[election]], wts = dec[['vap']],
            group = match_list
          ))`.
I wanted to confirm that you do not take intra-Census data into account for the disag process (e.g. for 2018 elections, disaggregting on some sort of 2018 demographic, like a voter file)? As I understand it, you use one ratio per block, dependent on which Census year and demographic are used (in build_dec and estimate_down, respectively). If you do integrate intra-decennial data, please let me know where I could find it in the code!

**Comment by christopherkenny** [comment]
Yes, you're correct. It's one ratio. There have been thoughts on doing it year-by-year, using the FCC estimates via @CoryMcCartan's `blockpop` package, but we haven't gone that way.

**Comment by spencer-rdh** [comment]
Great, was just looking to clarify -- thank you!

**Comment by christopherkenny** [comment]
No problem!
