### ISSUE TITLE
more detailed readme.md

### ISSUE THREAD

**Issue by rootsmusic** [alarm-redist/census-2020#2]
You've published your R codes.  For people who don't know R though, can the [readme.md](https://github.com/alarm-redist/census-2020/blob/main/vest-2020/README.md) please describe the code's logic in more detail?  Thanks.

**Comment by christopherkenny** [comment]
Is there something in particular that you'd like described? Happy to try to help, but it's not clear to me what additional information would be helpful.

**Comment by kosukeimai** [comment]
Yes, please be specific.  I'm closing this comment.  You can open a new issue if you have a specific request.
